apiVersion: apps/v1
Kind: Deployment
metadata:
  labels:
    app: vote
    tier: frontend
  name: vote
spec:
  replicas: 4
  template:
    spec:
      - name: vote
        containers:
          - image: schoolofdevops/vote:v3
            name: vote

