apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: frontend
  name: vote
spec:
  replicas: 2
  template:
    spec:
      - name: vote
        containers:
          - image: schoolofdevops/vote:v4
            name: vote

